"""Render a RunReport as Markdown for the human reviewer."""

from __future__ import annotations

from engineer.models.report import RunReport
from engineer.models.run import RunState

HUMAN_REVIEW_NOTICE = (
    "This change was generated by the autonomous engineering system and requires human "
    "review before merge."
)


def render_markdown(r: RunReport) -> str:
    ok = r.final_state == RunState.WAITING_FOR_HUMAN
    lines = [
        f"# Engineering run {r.run_id}",
        "",
        f"**Task:** {r.task_title}  ",
        f"**Final state:** `{r.final_state.value}`" + ("" if ok else " ❌"),
    ]
    if r.failure_reason:
        lines.append(f"  \n**Reason:** {r.failure_reason}")
    lines += [
        "",
        f"- Branch: `{r.branch or '-'}`",
        f"- Base commit: `{(r.base_commit or '-')[:12]}`  Head commit: "
        f"`{(r.head_commit or '-')[:12]}`",
        f"- Worktree: `{r.worktree_path or '-'}`",
        f"- Iterations: {r.iterations_used} / {r.max_iterations}",
        f"- Model calls: {r.usage.model_calls}, tokens in/out: {r.usage.input_tokens}/"
        f"{r.usage.output_tokens}, approx cost: ${r.usage.cost_usd:.4f}",
        f"- Tool calls: {r.usage.tool_calls} (policy denials: {r.policy_denials})",
        f"- Duration: {r.duration_seconds:.1f}s",
        "",
        "## Objective",
        "",
        r.plan.task_summary if r.plan else "(no plan was produced)",
        "",
    ]
    if r.plan:
        lines += ["## Plan", ""] + [f"{i}. {s}" for i, s in
                                    enumerate(r.plan.implementation_steps, 1)]
        if r.plan.assumptions:
            lines += ["", "**Assumptions:**"] + [f"- {a}" for a in r.plan.assumptions]
        if r.plan.uncertainty:
            lines += ["", f"**Planner uncertainty:** {r.plan.uncertainty}"]
        lines.append("")
    if r.engineer_summaries:
        lines += ["## Implementation", ""]
        lines += [f"- Iteration {i}: {s}" for i, s in enumerate(r.engineer_summaries, 1)]
        lines.append("")
    lines += ["## Files changed", ""]
    lines += [f"- `{f}`" for f in r.files_changed] or ["(none)"]
    if r.diff_stat:
        lines += ["", "```", r.diff_stat.rstrip(), "```"]
    lines += ["", "## Validation", ""]
    if r.final_validation:
        lines += ["| Check | Required | Result | Exit | Duration |", "|---|---|---|---|---|"]
        for v in r.final_validation.results:
            lines.append(f"| `{v.command_id}` | {'yes' if v.required else 'no'} | "
                         f"{'✅ pass' if v.passed else '❌ fail'} | {v.exit_code} | "
                         f"{v.duration_seconds:.1f}s |")
    else:
        lines.append("Validation did not run.")
    if r.diff_checks:
        lines += ["", "### Deterministic diff checks", ""]
        for c in r.diff_checks:
            mark = "✅" if c.passed else ("❌" if c.blocking else "⚠️")
            lines.append(f"- {mark} `{c.name}` — {c.detail}")
    if r.plan and r.plan.security_considerations:
        lines += ["", "## Security", ""] + [f"- {s}" for s in r.plan.security_considerations]
    lines += ["", "## Known limitations", ""]
    lines += [f"- {k}" for k in r.known_limitations] or ["- None recorded."]
    lines += ["", "## Human review required", "", HUMAN_REVIEW_NOTICE, ""]
    return "\n".join(lines)
